### PR TITLE
Update/v0.7.1-alpha

### PR DESCRIPTION
**Pull request by gStart9**

### CODE REVIEW

**Comment by gStart9** [comment]
Hey there @KoalaSat can I get a review on getting StartOS up to date for robosats-startos?
I tested this and it seems to work.

**Comment by KoalaSat** [comment]
Thanks @gStart9 !! It looks great, this release is still on pre-release because we are waiting for @Reckless-Satoshi to sign it and he is out for some time. 

I'll ping you here once we are ready. thanks again!

**Comment by gStart9** [comment]
I see 071 was released.  So in theory this should be good now, correct? I have not tested it since our convo 2 weeks ago.  Would the build on Dockerhub have changed?

**Comment by KoalaSat** [comment]
> I see 071 was released. So in theory this should be good now, correct? I have not tested it since our convo 2 weeks ago. Would the build on Dockerhub have changed?

Yes! Sorry by bad I remember yesterday about pinging here but then completely forgot 😞 

Would be better to use the new image because it includes our brand new coordinator

**Comment by KoalaSat** [comment]
Let's move this! 🙂

**Pull request merged**
